# Generated by Django 6.0.4 on 2026-07-27 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_paid', to='accounts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_splits', to='accounts.contact')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='accounts.transaction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_contact_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='transactionsplit',
            constraint=models.UniqueConstraint(fields=('transaction', 'contact'), name='unique_contact_per_transaction'),
        ),
    ]
