# Generated by Django 6.0.4 on 2026-08-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionsplit',
            old_name='signed_amount',
            new_name='amount',
        ),
    ]
