# Generated by Django 6.0.4 on 2026-08-21 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_signed_amount_transactionsplit_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='paid_by',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_paid_as_contact', to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_paid_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionsplit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_splits_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionsplit',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_splits_as_contact', to='accounts.contact'),
        ),
        migrations.AddConstraint(
            model_name='transactionsplit',
            constraint=models.UniqueConstraint(fields=('transaction', 'user'), name='unique_user_per_transaction'),
        ),
    ]
