# Generated by Django 6.0.4 on 2026-08-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_transaction_paid_by_transaction_payer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsplit',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='accounts.transaction'),
        ),
    ]
