# Generated by Django 6.0.4 on 2026-10-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transactionsplit_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsplit',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
