# Generated by Django 6.0.4 on 2026-10-04 16:58

from django.db import migrations, models


def migrate_settlement_data(apps, schema_editor):
    TransactionSplit = apps.get_model("accounts", "TransactionSplit")

    for split in TransactionSplit.objects.all():
        if split.settled:
            split.settled_amount = split.amount
        else:
            split.settled_amount = 0

        split.save(update_fields=["settled_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_transactionsplit_settled"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionsplit",
            name="settled_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
            ),
        ),

        migrations.RunPython(
            migrate_settlement_data,
            migrations.RunPython.noop,
        ),

        migrations.RemoveField(
            model_name="transactionsplit",
            name="settled",
        ),
    ]