# Generated by Django 6.0.4 on 2026-10-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_transactionsplit_settled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('lend', 'Lend'), ('borrow', 'Borrow')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_transactions', to='accounts.contact')),
            ],
        ),
    ]
